import assert from 'node:assert/strict';
import {createJCGuardian} from '../jc-guardian.js';
let now=1000;const events=[];
const g=createJCGuardian({clock:()=>now,report:e=>events.push(e),frameBudgetMs:20,maxConsecutiveSlowFrames:3,maxRecentFailures:2,cooldownMs:100});
assert.equal(g.position({x:0,y:1,z:2}),true);
assert.equal(g.position({x:NaN,y:1,z:2}),false);
assert.equal(g.position({x:5,y:0,z:0},{x:[0,4]}),false);
g.frame(30);g.frame(30);assert.equal(g.frame(30).ok,false);
assert.equal(events.filter(e=>e.type==='sustained-slow-frames').length,1);
assert.equal(g.frame(10).slowStreak,0);
let attempts=0;
assert.equal(g.execute('npc',()=>{attempts++;throw new Error('oops')},()=>42),42);
assert.equal(g.execute('npc',()=>{attempts++;throw new Error('oops')},()=>43),43);
assert.equal(g.execute('npc',()=>{attempts++;return 99},()=>44),44);
assert.equal(attempts,2,'open circuit must skip unsafe execution');
now+=101;
assert.equal(g.execute('npc',()=>99),99,'subsystem recovers after cooldown');
assert.equal(g.execute('safe',()=>7),7);
assert.equal(g.execute('fallback-throws',()=>{throw Error('bad')},()=>{throw Error('also bad')}),undefined);
const snapshot=g.snapshot();
assert.equal(snapshot.metrics.invalidPositions,2);
assert.equal(snapshot.metrics.recoveries,3);
assert.ok(snapshot.incidents.length>=4);
console.log('PASS: Guardian coordinate limits, stall detection, isolated failures, circuit cooldown, fallback containment');
