import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {abilityWheelPage,minimapPoint,compassHeading} from '../jc-hud-model.js';

const abilities=Array.from({length:17},(_,i)=>({id:i,group:'JC'}));
assert.deepEqual(abilityWheelPage(abilities,'JC',0).items.map(x=>x.id),[0,1,2,3,4,5,6,7]);
assert.deepEqual(abilityWheelPage(abilities,'JC',2).items.map(x=>x.id),[16]);
assert.deepEqual(abilityWheelPage(abilities,'JC',-1).items.map(x=>x.id),[16]);
for(const index of [Infinity,NaN,-Infinity])assert.equal(abilityWheelPage(abilities,'JC',index).page,0);
for(const size of [0,NaN,Infinity])assert.equal(abilityWheelPage(abilities,'JC',2,size).pageCount,3);
assert.equal(abilityWheelPage(abilities,'JC',0,2).items.length,2);
assert.equal(abilityWheelPage(abilities,'JC',0,1.5).items.length,1);
assert.equal(abilityWheelPage(abilities,'JC',0,100000).items.length,17);
assert.deepEqual(abilityWheelPage(null,'JC'),{items:[],page:0,pageCount:1});
assert.deepEqual(abilityWheelPage([null,undefined,{id:'a',group:'JC'}],'JC').items,[{id:'a',group:'JC'}]);
assert.deepEqual(abilityWheelPage(abilities,'missing'),{items:[],page:0,pageCount:1});
assert.deepEqual(minimapPoint({x:100,z:50},{x:100,z:50},150,200),{x:100,y:100});
assert.deepEqual(minimapPoint({x:250,z:-100},{x:100,z:50},150,200),{x:200,y:0});
for(const input of [null,undefined,{x:NaN,z:0},{x:Infinity,z:0},{x:0,z:-Infinity}])assert.deepEqual(minimapPoint(input,{x:0,z:0},150,200),{x:-1e6,y:-1e6});
for(const range of [0,-1,NaN,Infinity])assert.deepEqual(minimapPoint({x:1,z:1},{x:0,z:0},range,200),{x:-1e6,y:-1e6});
for(const size of [0,-1,NaN,Infinity])assert.deepEqual(minimapPoint({x:1,z:1},{x:0,z:0},150,size),{x:-1e6,y:-1e6});
assert.deepEqual(minimapPoint({x:1e308,z:0},{x:-1e308,z:0},150,200),{x:-1e6,y:-1e6});
assert.equal(compassHeading(0),0);
assert.equal(compassHeading(Math.PI/2),90);
assert.equal(compassHeading(-Math.PI/2),270);
assert.equal(compassHeading(2*Math.PI),0);
for(const value of [NaN,Infinity,-Infinity,undefined,null,'90'])assert.equal(compassHeading(value),0);
assert.equal(readFileSync(new URL('../jc-hud-model.js',import.meta.url),'utf8'),readFileSync(new URL('../dist/client/jc-hud-model.js',import.meta.url),'utf8'),'authored and deployable HUD modules must match');
console.log('PASS: HUD input guards, wheel pagination, minimap coordinates, compass heading, and deployable parity.');
