import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const engine=fs.readFileSync(new URL('../map-engine.js',import.meta.url),'utf8');
const samples=[];
const context=vm.createContext({last:0,requestAnimationFrame(){},tick:dt=>samples.push(dt),streamingTick(){},controls:{update(){}},renderer:{render(){}},scene:{},camera:{},mobileMap:false,startInPlay:true,document:{body:{classList:{contains:()=>true}}},window:{JC_MAP_PLAYING:true,JC_PLAYER_READY:true,JC_WORLD_SCALE:.22,studio:{paused:false,renderFrame(){}}}});
vm.runInContext(engine.slice(engine.indexOf('function animate(t)'),engine.indexOf('window.studio={')),context);
context.animate(40);assert.ok(Math.abs(samples.at(-1)-.0088)<1e-9,'slow time reduces debris simulation speed');
context.window.JC_WORLD_SCALE=0;context.animate(80);assert.equal(samples.at(-1),0,'stasis or UI pause stops debris');
context.window.JC_WORLD_SCALE=1;context.animate(120);assert.equal(samples.at(-1),.04,'normal world speed resumes');
context.window.JC_WORLD_SCALE=10;context.animate(160);assert.equal(samples.at(-1),.04,'world speed stays inside its physics budget');
const look=fs.readFileSync(new URL('../cinematic-look.js',import.meta.url),'utf8');
const gameplay=fs.readFileSync(new URL('../jc-map-game.js',import.meta.url),'utf8');
assert.match(look,/function setTimeOfDay\(mode='night'\)/,'cinematic renderer exposes persistent day/night selection');
assert.match(look,/mode==='day'[\s\S]*?scene\.background=daySky/,'daylight has an explicit bright sky path');
assert.match(gameplay,/id="jcTimeToggle"/,'game settings expose the day/night control');
assert.match(gameplay,/let worldTimeMode='day'/,'fresh sessions can boot directly into daylight');
const startup=fs.readFileSync(new URL('../map-startup.js',import.meta.url),'utf8');
assert.doesNotMatch(startup,/setTimeout\(\(\)=>window\.jcOpenLiteFallback\('startup-timeout'\)/,'slow full-3D startup no longer auto-redirects to lite mode');
assert.match(startup,/\},90000\);/,'full-3D startup watchdog allows the current 90-second recovery window');
assert.match(gameplay,/window\.JC_BOOT_STAGE='player-ready'/,'boot exposes the player-ready milestone');
console.log('PASS: world slowdown, stasis, pause/resume, bounded physics timing, and persistent daylight mode.');
